/* eslint-disable @next/next/no-css-tags */
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Script from "next/script";
import Providers from "@/components/Providers";
import "./globals.css";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Buddy Script",
    description: "Generated by create next app",
    icons: {
        icon: "/assets/images/logo-copy.svg",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${poppins.variable}`}>
            <head>
                <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
                <link rel="stylesheet" href="/assets/css/common.css" />
                <link rel="stylesheet" href="/assets/css/main.css" />
                <link rel="stylesheet" href="/assets/css/responsive.css" />
            </head>
            <body>
                <Providers>{children}</Providers>
                <Script
                    src="/assets/js/bootstrap.bundle.min.js"
                    strategy="afterInteractive"
                />
                <Script src="/assets/js/custom.js" strategy="afterInteractive" />
            </body>
        </html>
    );
}
